spring:
  application:
    name: student-service
  cloud:
    config:
      name: ${spring.application.name}
      label: ${spring.profiles.active}
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
