server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      label: ${APP_ENV:staging}
      server:
        git:
          uri: ${URI:https://github.com/amartins-alexandre/config-repo.git}
          search-paths:
          - ms-one
          - ms-two
